### ISSUE TITLE
Integration with Glimp

### ISSUE THREAD

**Issue by maerlyn13** [PedanticAvenger/FlashCGM#25]
Is there a way to implement syncing with Glimp to show glucose values by dropbox and not nightscout since it is possible for glimp to share values this way? On the watchface for fitbit that you have created. Please let me know as I do not have a nightscout account.

**Comment by PedanticAvenger** [comment]
Unfortunately no.  The watchface depends on a web server API to get the data and I don't believe Glimp will provide such an interface on the app, if you are uncomfortable using xDrip+ instead of Glimp then I believe the least painful option forward is to setup a nightscout site as Glimp should be able to push data there.
